- name: Install dependencies
  hosts: localhost
  tasks:
    - name: Add lwh epository
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:lakinduakash/lwh
        codename: jammy # Note: this may be different
        state: present
    - name: Install packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - linux-headers-6.1.0-37-amd64
        - build-essential
        - git
        - dkms
        - dos2unix
        - openvpn
        - openvpn-systemd-resolved
        - linux-wifi-hotspot

- name: Configure VPN
  hosts: localhost
  tasks:
    - name: Copy client configuration
      become: true
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'VPN_CONF') }}"
        dest: /etc/openvpn/client/client.conf
    - name: Enable VPN service
      become: true
      ansible.builtin.service:
        name: openvpn-client@client.service
        state: restarted
        enabled: true

- name: Install wifi USB drivers
  hosts: localhost
  tasks:
    - name: Clone driver repo
      ansible.builtin.git:
        repo: https://github.com/lwfinger/rtw88
        dest: ./rtw88
    - name: Ensure configuration has no CR
      ansible.builtin.shell:
        cmd: dos2unix dkms.conf
        chdir: ./rtw88
    - name: Install driver
      become: true
      ansible.builtin.shell:
        cmd: dkms install $PWD
        chdir: ./rtw88
    - name: Install firmware
      become: true
      ansible.builtin.shell:
        cmd: make install_fw
        chdir: ./rtw88
    - name: Copy configuration
      become: true
      ansible.builtin.shell:
        cmd: cp rtw88.conf /etc/modprobe.d/
        chdir: ./rtw88

- name: Configure hotspot
  hosts: localhost
  tasks:
    - name: Configure AP settings
      become: true
      ansible.builtin.command: "create_ap WHICH_INTERFACE tun0 {{ lookup('ansible.builtin.env', 'AP_SSID') }} {{ lookup('ansible.builtin.env', 'AP_PASSWORD') }}"
    - name: Enable create_ap service
      become: true
      ansible.builtin.service:
        name: create_ap
        state: started
        enabled: true