- name: Install dependencies
  hosts: localhost
  tasks:
    - name: Add lwh epository
      become: true
      ansible.builtin.apt_repository:
        repo: ppa:lakinduakash/lwh
        codename: jammy # Note: this may be different
        state: present
    - name: Install packages
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - dnsmasq
        - openvpn
        - openvpn-systemd-resolved
        - linux-wifi-hotspot

- name: Configure VPN
  hosts: localhost
  tasks:
    - name: Copy client configuration
      become: true
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'VPN_CONF') }}"
        dest: /etc/openvpn/client/client.conf
    - name: Enable VPN service
      become: true
      ansible.builtin.service:
        name: openvpn-client@client.service
        state: restarted
        enabled: true

- name: Configure hotspot
  hosts: localhost
  tasks:
    - name: Configure AP settings
      become: true
      ansible.builtin.shell: "create_ap wlx98ba5fd1e0ec tun0 {{ lookup('ansible.builtin.env', 'AP_SSID') }} {{ lookup('ansible.builtin.env', 'AP_PASSWORD') }} &"
    - name: Enable create_ap service
      become: true
      ansible.builtin.service:
        name: create_ap
        state: started
        enabled: true